// <auto-generated />
namespace HeroesAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add2PropertiesToHero : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add2PropertiesToHero));
        
        string IMigrationMetadata.Id
        {
            get { return "202101201744370_add2PropertiesToHero"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
